# This workflow will:
# - run unit tests, 
# - build the container 
# - run a short smoke test

on:
  push:
    branches:
      - master

name: Simple CI

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: unit test
      run: |
        make dunit

    - name: build container
      id: build-image
      run: |
        make dtest